# Generated by Django 5.1 on 2024-08-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_customer_customer_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='meter_serial',
            field=models.CharField(max_length=50),
        ),
    ]
