# Generated by Django 5.1 on 2024-10-12 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_fiscalyearrecord_ledgerentry_advance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='advance',
        ),
        migrations.AlterField(
            model_name='administrativecharge',
            name='charge_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 4, 7, 7, 722892, tzinfo=datetime.timezone.utc)),
        ),
    ]
