# Generated by Django 5.1 on 2024-10-12 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_ledgerentry_advance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='meterreading',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativecharge',
            name='charge_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 17, 28, 51, 341581, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
