# Generated by Django 5.1 on 2024-10-14 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_meterreading_payment_status_meterreading_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('days_array', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='administrativecharge',
            name='charge_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 18, 12, 59, 620436, tzinfo=datetime.timezone.utc)),
        ),
    ]
