# Generated by Django 5.1 on 2024-10-16 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_fiscalcalendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSADMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_month', models.IntegerField()),
                ('bs_year', models.IntegerField()),
                ('ad_month_start', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='administrativecharge',
            name='charge_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 12, 29, 9, 608824, tzinfo=datetime.timezone.utc)),
        ),
    ]
