import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from '@/components/providers';
import Navigationbar from "@/components/navigationbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sycas",
  description: "Generated by Sycas Company",
  icons: {
    icon: '/sycas-halflogo.svg', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  >
      <body className={inter.className}>
      <Providers>
      <Navigationbar />
        {children}
        <Footer />
      </Providers>
      </body>
    </html>
  );
}
